"""Entry point for the PMO Program Intelligence Crew backend.

Two documented commands:

    python main.py serve            # run the FastAPI app (default)
    python main.py run              # one live kickoff over the synthetic dataset,
                                    # prints the DRAFT readout and saves it to docs/

`run` executes the capstone scenario end to end (deterministic ingestion +
analysis, then the Narrative crew) and writes the result to
docs/sample-readout.md and docs/sample-run.json for review. It requires a funded
OPENAI_API_KEY in backend/.env (the Narrative step calls the model).

Equivalent server command: uvicorn src.app:app --host 127.0.0.1 --port 8000
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def _serve() -> None:
    import uvicorn

    uvicorn.run(
        "src.app:app",
        host=os.getenv("HOST", "127.0.0.1"),
        port=int(os.getenv("PORT", "8000")),
        reload=False,
    )


def _run_once() -> int:
    """Execute one capstone readout and save the output. Returns a process exit code."""
    from dotenv import load_dotenv

    load_dotenv()

    from src.orchestrator import MissingApiKeyError, run_readout

    repo_root = Path(__file__).resolve().parent.parent
    docs = repo_root / "docs"
    docs.mkdir(exist_ok=True)
    md_path = docs / "sample-readout.md"
    json_path = docs / "sample-run.json"

    try:
        result = run_readout(inputs={})
    except MissingApiKeyError as exc:
        print(f"[run] cannot run the Narrative step: {exc}", file=sys.stderr)
        print("[run] set a funded OPENAI_API_KEY in backend/.env and retry.", file=sys.stderr)
        return 2

    envelope = result.model_dump(exclude_none=True)
    json_path.write_text(json.dumps(envelope, indent=2), encoding="utf-8")

    if result.status == "HALTED":
        diag = result.diagnostic
        print(f"[run] run HALTED at step '{diag.failedWorkstream}': {diag.reason}", file=sys.stderr)
        print(f"[run] envelope saved to {json_path}", file=sys.stderr)
        return 1

    # AWAITING_APPROVAL: save the human-readable DRAFT readout.
    draft = result.draft
    header = (
        "<!-- Generated by `python main.py run` over the synthetic dataset in data/.\n"
        f"     runId: {result.runId} | run status: {result.status} | "
        f"draft.status: {draft.status}. This is a saved sample for review. -->\n\n"
    )
    md_path.write_text(header + draft.markdown + "\n", encoding="utf-8")

    print(f"[run] runId={result.runId} status={result.status}")
    print(f"[run] saved readout -> {md_path}")
    print(f"[run] saved envelope -> {json_path}")
    print()
    print(draft.markdown)
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="PMO Program Intelligence Crew backend")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("serve", help="run the FastAPI app (default)")
    sub.add_parser("run", help="one live kickoff over the synthetic dataset; saves the readout")

    args = parser.parse_args()
    command = args.command or "serve"

    if command == "run":
        raise SystemExit(_run_once())
    _serve()


if __name__ == "__main__":
    main()
